/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inf;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author Hasindu Thirasara
 */
public class Activity extends javax.swing.JFrame {
    private final String dbUrl = "jdbc:mysql://localhost:3306/bhsm";
    private final String dbUsername = "root";
    private final String dbPassword = "root";
  
    /**
     * Creates new form Activity
     */
    public Activity() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSpecialNote = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtActivityNo = new javax.swing.JTextField();
        txtTenantIDActivity = new javax.swing.JTextField();
        txtActivityDate = new javax.swing.JTextField();
        txtTimeArrived = new javax.swing.JTextField();
        txtTimeLeft = new javax.swing.JTextField();
        menubtn = new javax.swing.JButton();
        addbtn1 = new javax.swing.JButton();
        cleartn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        jLabel1.setText("ACTIVITY");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(532, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Special Note :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));
        jPanel1.add(txtSpecialNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 300, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Activity No :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tenant ID :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 60, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Time Arrived :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Time Left :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));
        jPanel1.add(txtActivityNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 300, -1));
        jPanel1.add(txtTenantIDActivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 300, -1));
        jPanel1.add(txtActivityDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 300, -1));
        jPanel1.add(txtTimeArrived, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 300, -1));
        jPanel1.add(txtTimeLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 300, -1));

        menubtn.setBackground(new java.awt.Color(0, 153, 153));
        menubtn.setText("Menu");
        menubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menubtnActionPerformed(evt);
            }
        });
        jPanel1.add(menubtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 190, 40));

        addbtn1.setBackground(new java.awt.Color(0, 153, 153));
        addbtn1.setText("ADD");
        addbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(addbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 70, 50));

        cleartn.setBackground(new java.awt.Color(0, 153, 153));
        cleartn.setText("CLEAR");
        cleartn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleartnActionPerformed(evt);
            }
        });
        jPanel1.add(cleartn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(815, 472));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cleartnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleartnActionPerformed
                int msg=JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to Clear the form?",
                        "Update Confirmation", JOptionPane.YES_NO_OPTION);
                
                //if they press yes then make the connection and delete it.
                if (msg==0)
                {
        
                txtActivityNo.setText("");
                txtTenantIDActivity.setText("");
                txtActivityDate.setText("");
                txtTimeArrived.setText("");
                txtTimeLeft.setText("");
                txtSpecialNote.setText("");
                }
    }//GEN-LAST:event_cleartnActionPerformed

    private void addbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtn1ActionPerformed
        // TODO add your handling code here:
        try{
                    Connection conn = DriverManager.getConnection(dbUrl, dbUsername, dbPassword);
                    LocalDate inputDate = LocalDate.parse(txtActivityDate.getText());
                    LocalDate currentDate = LocalDate.now(); // Current date
                    
                    if (("".equals(txtActivityNo.getText()))||(txtTenantIDActivity.getText()=="")||(txtActivityDate.getText()=="")||(txtTimeArrived.getText()=="")||(txtTimeLeft.getText()=="")||(txtSpecialNote.getText()==""))
                    {
                        JOptionPane.showMessageDialog(null,"Please Fill all the data");
                    }
                    
                    else if (!inputDate.isEqual(currentDate)) {
                    JOptionPane.showMessageDialog(this, "Entered date is not the current date.");
                    } 
                    else
                    {
                    
                    //get the values from database into array
                    java.sql.PreparedStatement pst1 = conn.prepareStatement( "INSERT INTO Payment VALUES (?,?,?,?,?,?)");
                    pst1.setString(1,txtActivityNo.getText());
                    pst1.setString(2, txtActivityDate.getText());
                    pst1.setString(3, txtTimeLeft.getText());
                    pst1.setString(4, txtTimeArrived.getText());
                    pst1.setString(5, txtSpecialNote.getText());
                    pst1.setString(6, txtTenantIDActivity.getText());
                    
                    pst1.executeUpdate();
                    JOptionPane.showMessageDialog(null,"Data Inserted Successfully");
                    
                    txtActivityNo.setText("");
                    txtActivityDate.setText("");
                    txtTimeLeft.setText("");
                    txtTimeArrived.setText("");
                    txtSpecialNote.setText("");
                    txtTenantIDActivity.setText("");
                    
                    conn.close();
                    
                   
                    
         }
         } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "SQL Error");
            
         }
        // handle invalid date exception
            catch (DateTimeParseException ex) {
            JOptionPane.showMessageDialog(this, "Invalid date format. Please enter date in yyyy-MM-dd format.");
            }
        
       
                
        
    }//GEN-LAST:event_addbtn1ActionPerformed

    private void menubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menubtnActionPerformed
        int msg=JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to return to the menu?",
                        "Update Confirmation", JOptionPane.YES_NO_OPTION);
                
                //if they press yes then make the connection and delete it.
                if (msg==0)
                {
                Menu wid1 = new Menu();
                wid1.setVisible(true);
                this.setVisible(false);
                
    }    
    }//GEN-LAST:event_menubtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Activity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn1;
    private javax.swing.JButton cleartn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton menubtn;
    private javax.swing.JTextField txtActivityDate;
    private javax.swing.JTextField txtActivityNo;
    private javax.swing.JTextField txtSpecialNote;
    private javax.swing.JTextField txtTenantIDActivity;
    private javax.swing.JTextField txtTimeArrived;
    private javax.swing.JTextField txtTimeLeft;
    // End of variables declaration//GEN-END:variables
}
