/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package inf;

import javax.swing.JOptionPane;

/**
 *
 * @author Hasindu Thirasara
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        btnTenantDetail = new javax.swing.JButton();
        btnRoomManagement = new javax.swing.JButton();
        btnMaintenance = new javax.swing.JButton();
        btnPayments = new javax.swing.JButton();
        btnActivity = new javax.swing.JButton();
        btnVisitor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 42)); // NOI18N
        jLabel1.setText("MAIN MENU");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(525, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 120));

        btnHome.setBackground(new java.awt.Color(0, 153, 153));
        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHome.setText("HOME");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 320, 40));

        btnTenantDetail.setBackground(new java.awt.Color(0, 153, 153));
        btnTenantDetail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTenantDetail.setText("TENANT'S DETAILS");
        btnTenantDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTenantDetailActionPerformed(evt);
            }
        });
        jPanel1.add(btnTenantDetail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 320, 40));

        btnRoomManagement.setBackground(new java.awt.Color(0, 153, 153));
        btnRoomManagement.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRoomManagement.setText("ROOM MANAGEMENT");
        btnRoomManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRoomManagementActionPerformed(evt);
            }
        });
        jPanel1.add(btnRoomManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 320, 40));

        btnMaintenance.setBackground(new java.awt.Color(0, 153, 153));
        btnMaintenance.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMaintenance.setText("MAINTAINANCE");
        btnMaintenance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaintenanceActionPerformed(evt);
            }
        });
        jPanel1.add(btnMaintenance, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 320, 40));

        btnPayments.setBackground(new java.awt.Color(0, 153, 153));
        btnPayments.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPayments.setText("PAYMENTS");
        btnPayments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentsActionPerformed(evt);
            }
        });
        jPanel1.add(btnPayments, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 320, 40));

        btnActivity.setBackground(new java.awt.Color(0, 153, 153));
        btnActivity.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnActivity.setText("ACTIVITY");
        btnActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivityActionPerformed(evt);
            }
        });
        jPanel1.add(btnActivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 320, 40));

        btnVisitor.setBackground(new java.awt.Color(0, 153, 153));
        btnVisitor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVisitor.setText("VISITOR");
        btnVisitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitorActionPerformed(evt);
            }
        });
        jPanel1.add(btnVisitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 320, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(844, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTenantDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTenantDetailActionPerformed
        // TODO add your handling code here:
        TennantDetails wid1 = new TennantDetails();
        wid1.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnTenantDetailActionPerformed

    private void btnMaintenanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaintenanceActionPerformed
        // TODO add your handling code here:
        Maintenance wid1 = new Maintenance ();
        wid1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMaintenanceActionPerformed

    private void btnPaymentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentsActionPerformed
        // TODO add your handling code here:
        payment wid1 = new payment ();
        wid1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPaymentsActionPerformed

    private void btnActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivityActionPerformed
        // TODO add your handling code here:
        Activity wid1 = new Activity ();
        wid1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnActivityActionPerformed

    private void btnVisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitorActionPerformed
        // TODO add your handling code here:
        visitor wid1 = new visitor ();
        wid1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVisitorActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        int msg=JOptionPane.showConfirmDialog(rootPane, "Are you sure you want to return to Home?",
                        "Update Confirmation", JOptionPane.YES_NO_OPTION);
                
                //if they press yes then make the connection and delete it.
                if (msg==0)
                {
                Login wid1 =new Login();
                wid1.setVisible(true);
                this.setVisible(false);
                
                }        
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnRoomManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRoomManagementActionPerformed
    Room_Management wid1 = new Room_Management();
    wid1.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_btnRoomManagementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivity;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnMaintenance;
    private javax.swing.JButton btnPayments;
    private javax.swing.JButton btnRoomManagement;
    private javax.swing.JButton btnTenantDetail;
    private javax.swing.JButton btnVisitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
